name: Automate Workflow
on:
  push:
    branches: [ main ]

jobs:
  linter:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      -   name: Checkout Code
          uses: actions/checkout@v4
      -   name: Setup Java17
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'zulu'
      -   name: Run Linter
          working-directory: ./posttest
          run: ./gradlew spotlessCheck
  unit-test:
    name: Run Unit Test
    runs-on: ubuntu-latest
    needs:
      - linter
    steps:
      -   name: Checkout Code
          uses: actions/checkout@v4
      -   name: Setup Java17
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'zulu'
      -   name: Run Unit Tests
          working-directory: ./posttest
          run: ./gradlew test
          env:
            SPRING_PROFILES_ACTIVE: test
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs:
      - linter
      - unit-test
    steps:
      -   name: Checkout Code
          uses: actions/checkout@v4
      -   name: Build Docker image
          working-directory: ./posttest
          run: docker build -f Dockerfile.multi -t posttest:latest .